import { emptyFilters } from '../../constants/filters';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock, FileText, Send, Upload, Wallet } from 'lucide-react';
import { Avatar, Button, KPIWidget, Modal, SectionHeader, cardStyles, tableStyles } from '../../components/SharedUI';
import { FilterBar } from '../../components/FilterBar';
import { ImageUpload } from '../../components/ImageUpload';
import { userService } from '../../services/userService';
import { draftService } from '../../services/draftService';
import { kolService } from '../../services/kolService';
import { metricService } from '../../services/metricService';
import { paymentService, type PaymentWithRelations } from '../../services/paymentService';
import { postService } from '../../services/postService';
import { taskService } from '../../services/taskService';
import { formatCurrency, formatDate, getErrorMessage, paymentStatusLabels, statusBadgeClass, taskStatusLabels } from '../../constants/domain';
import type { AppUser, KolWithUser, ReportPeriod, TaskWithRelations } from '../../types/database';

type KolView = 'dashboard' | 'profile' | 'tasks' | 'payment';
type Action = { type: 'draft' | 'publish' | 'metrics'; task: TaskWithRelations } | null;
interface Props { initialView?: string; user: AppUser }

function Empty({ text }: { text: string }) { return <div className="py-12 text-center text-sm text-slate-400">{text}</div>; }

export function KOLDashboard({ initialView = 'dashboard', user }: Props) {
  const view = (['dashboard', 'profile', 'tasks', 'payment'].includes(initialView) ? initialView : 'dashboard') as KolView;
  const [filters, setFilters] = useState({ ...emptyFilters });
  const [profile, setProfile] = useState<KolWithUser | null>(null);
  const [tasks, setTasks] = useState<TaskWithRelations[]>([]);
  const [payments, setPayments] = useState<PaymentWithRelations[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    try {
      setLoading(true); setError('');
      const current = await kolService.getByUserId(user.id);
      const [taskRows, paymentRows] = await Promise.all([taskService.getTasksByKol(current.id), paymentService.getPaymentsByKOL(current.id)]);
      setProfile(current); setTasks(taskRows); setPayments(paymentRows);
    } catch (caught) { setError(`Không thể tải dữ liệu: ${getErrorMessage(caught)}`); }
    finally { setLoading(false); }
  }, [user.id]);

  useEffect(() => { void load(); window.addEventListener('kollab:refresh', load); return () => window.removeEventListener('kollab:refresh', load); }, [load]);
  if (loading) return <div className="space-y-4"><div className="skeleton h-9 w-56" /><div className="grid grid-cols-3 gap-4">{[1, 2, 3].map(i => <div key={i} className="skeleton h-28" />)}</div><div className="skeleton h-80" /></div>;
  if (!profile) return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700">{error || 'Tài khoản chưa có hồ sơ KOL/KOC.'}<button onClick={() => void load()} className="ml-3 underline font-semibold">Tải lại</button></div>;

  const match = (text: string) => text.toLocaleLowerCase('vi').includes(filters.query.trim().toLocaleLowerCase('vi'));
  const filteredTasks = tasks.filter(t => match(`${t.campaigns?.campaign_name} ${t.campaigns?.brands?.brand_name} ${t.content_requirement} ${t.content_type}`) && (!filters.status || t.status === filters.status) && (!filters.campaign || String(t.campaign_id) === filters.campaign));
  const filteredPayments = payments.filter(p => match(`${p.campaign_tasks?.campaigns?.campaign_name} ${p.brands?.brand_name}`) && (!filters.status || p.status === filters.status));
  const campaigns = [...new Map(tasks.map(t => [t.campaign_id, { value: String(t.campaign_id), label: t.campaigns?.campaign_name ?? 'Chiến dịch' }])).values()];
  return <>{error && <div className="mb-4 badge-danger p-3">{error}</div>}{['tasks','payment'].includes(view) && <FilterBar value={filters} onChange={setFilters} statuses={Object.entries(view === 'payment' ? paymentStatusLabels : taskStatusLabels).map(([value,label]) => ({ value,label }))} campaigns={view === 'tasks' ? campaigns : undefined} />}{view === 'dashboard' && <Dashboard profile={profile} tasks={tasks} payments={payments} />}{view === 'profile' && <Profile profile={profile} reload={load} />}{view === 'tasks' && <Tasks tasks={filteredTasks} reload={load} />}{view === 'payment' && <Payments payments={filteredPayments} />}</>;
}

function Dashboard({ profile, tasks, payments }: { profile: KolWithUser; tasks: TaskWithRelations[]; payments: PaymentWithRelations[] }) {
  const paid = payments.reduce((sum, p) => sum + Number(p.paid_amount), 0);
  const pending = payments.reduce((sum, p) => sum + Math.max(0, Number(p.amount) - Number(p.paid_amount)), 0);
  return <div className="space-y-6"><SectionHeader title={`Xin chào, ${profile.users?.full_name ?? 'Creator'}`} subtitle="Theo dõi công việc và thu nhập của bạn" /><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><KPIWidget label="Nhiệm vụ" value={String(tasks.length)} icon={<FileText className="w-4 h-4" />} role="kol" /><KPIWidget label="Đang thực hiện" value={String(tasks.filter(t => !['COMPLETED', 'PAID', 'CANCELLED'].includes(t.status)).length)} icon={<Clock className="w-4 h-4" />} role="kol" /><KPIWidget label="Đã nhận" value={formatCurrency(paid)} icon={<CheckCircle2 className="w-4 h-4" />} role="kol" /><KPIWidget label="Chờ thanh toán" value={formatCurrency(pending)} icon={<Wallet className="w-4 h-4" />} role="kol" /></div><div className={`${cardStyles.container} p-5`}><h3 className="font-bold text-slate-900 dark:text-white mb-4">Nhiệm vụ gần đây</h3>{tasks.slice(0, 5).map(task => <div key={task.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 py-3 border-b border-slate-100 dark:border-slate-700 last:border-0"><div><p className="text-sm font-semibold text-slate-900 dark:text-white">{task.campaigns?.campaign_name ?? 'Chiến dịch'}</p><p className="text-xs text-slate-400">{task.campaigns?.brands?.brand_name ?? 'Brand'} • Hạn draft {formatDate(task.draft_deadline)}</p></div><span className={statusBadgeClass(task.status)}>{taskStatusLabels[task.status]}</span></div>)}{tasks.length === 0 && <Empty text="Bạn chưa được giao nhiệm vụ nào" />}</div></div>;
}

function Profile({ profile, reload }: { profile: KolWithUser; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ avatar_url: profile.users?.avatar_url ?? '', bio: profile.bio ?? '', platform: profile.platform ?? '', social_link: profile.social_link ?? '', followers: String(profile.followers), content_category: profile.content_category ?? '', qr_payment_url: profile.qr_payment_url ?? '', bank_name: profile.bank_name ?? '', bank_account: profile.bank_account ?? '', bank_owner: profile.bank_owner ?? '' });
  const [uploading, setUploading] = useState(false);
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const save = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); setError(''); const { avatar_url, ...profileInput } = form; await userService.update(profile.user_id, { avatar_url: avatar_url || null }); window.dispatchEvent(new Event('kollab:user-updated')); await kolService.update(profile.id, { ...profileInput, followers: Number(form.followers), social_link: form.social_link || null, qr_payment_url: form.qr_payment_url || null }); await reload(); setEditing(false); } catch (caught) { setError(getErrorMessage(caught)); } finally { setSaving(false); } };
  return <div><SectionHeader title="Hồ sơ & Thông tin" subtitle="Thông tin creator và tài khoản nhận thanh toán" action={!editing ? <Button role="kol" onClick={() => setEditing(true)}>Chỉnh sửa</Button> : undefined} /><div className={`${cardStyles.container} p-6`}><div className="flex items-center gap-4 mb-6"><Avatar role="kol" size="xl" initials={(profile.users?.full_name ?? 'KO').slice(0, 2).toUpperCase()} image={profile.users?.avatar_url ?? undefined} /><div><h2 className="text-xl font-bold text-slate-900 dark:text-white">{profile.users?.full_name}</h2><p className="text-sm text-slate-500">{profile.users?.email}</p><p className="text-sm text-blue-600 mt-1">{profile.platform} • {profile.followers.toLocaleString()} followers</p></div></div>{editing ? <form onSubmit={save} className="space-y-4"><ImageUpload label="Ảnh đại diện" folder="avatars" value={form.avatar_url} onChange={url => setForm(f => ({ ...f, avatar_url: url }))} onBusyChange={setUploading} /><div><label className="input-label">Giới thiệu</label><textarea rows={3} className="input-base" value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} /></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Nền tảng" value={form.platform} set={v => setForm({ ...form, platform: v })} /><Field label="Followers" type="number" value={form.followers} set={v => setForm({ ...form, followers: v })} /><Field label="Chuyên mục" value={form.content_category} set={v => setForm({ ...form, content_category: v })} /><Field label="Link mạng xã hội" type="url" value={form.social_link} set={v => setForm({ ...form, social_link: v })} /><Field label="Ngân hàng" value={form.bank_name} set={v => setForm({ ...form, bank_name: v })} /><Field label="Số tài khoản" value={form.bank_account} set={v => setForm({ ...form, bank_account: v })} /><Field label="Chủ tài khoản" value={form.bank_owner} set={v => setForm({ ...form, bank_owner: v })} /><Field label="URL QR thanh toán" type="url" value={form.qr_payment_url} set={v => setForm({ ...form, qr_payment_url: v })} /></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditing(false)}>Hủy</Button><button disabled={saving || uploading} type="submit" className="btn-primary bg-blue-500 hover:bg-blue-600">{saving ? 'Đang lưu...' : 'Lưu hồ sơ'}</button></div></form> : <div className="grid sm:grid-cols-2 gap-4">{[['Giới thiệu', profile.bio], ['Chuyên mục', profile.content_category], ['Link mạng xã hội', profile.social_link], ['Ngân hàng', profile.bank_name], ['Số tài khoản', profile.bank_account], ['Chủ tài khoản', profile.bank_owner]].map(([label, value]) => <div key={label} className="surface-subtle p-4"><p className="text-xs uppercase font-semibold text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-800 dark:text-white break-all">{value || 'Chưa cập nhật'}</p></div>)}</div>}</div></div>;
}

function Field({ label, value, set, type = 'text' }: { label: string; value: string; set: (value: string) => void; type?: string }) { return <div><label className="input-label">{label}</label><input required={label.includes('*')} min={type === 'number' ? 0 : undefined} step={type === 'number' ? 1 : undefined} type={type} className="input-base" value={value} onChange={e => set(e.target.value)} /></div>; }

function Tasks({ tasks, reload }: { tasks: TaskWithRelations[]; reload: () => Promise<void> }) {
  const [action, setAction] = useState<Action>(null);
  const actionFor = (task: TaskWithRelations) => {
    if (['ASSIGNED', 'REVISION_REQUIRED'].includes(task.status)) return <Button role="kol" size="sm" onClick={() => setAction({ type: 'draft', task })} icon={<Upload className="w-4 h-4" />}>Nộp draft</Button>;
    if (task.status === 'APPROVED_TO_PUBLISH') return <Button role="kol" size="sm" onClick={() => setAction({ type: 'publish', task })} icon={<Send className="w-4 h-4" />}>Gửi link bài đăng</Button>;
    if (['PUBLISHED', 'TRACKING'].includes(task.status)) return <Button role="kol" size="sm" onClick={() => setAction({ type: 'metrics', task })} icon={<FileText className="w-4 h-4" />}>Gửi metrics</Button>;
    return null;
  };
  return <div><SectionHeader title="Nhiệm vụ của tôi" subtitle={`${tasks.length} nhiệm vụ được giao từ Brand`} /><div className="space-y-4">{tasks.map(task => { const latestDraft = [...(task.draft_submissions ?? [])].sort((a, b) => Date.parse(b.submitted_at) - Date.parse(a.submitted_at) || b.id - a.id)[0]; return <div key={task.id} className={`${cardStyles.container} p-5`}><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="space-y-2"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-bold text-slate-900 dark:text-white">{task.campaigns?.campaign_name ?? 'Chiến dịch'}</h3><span className={statusBadgeClass(task.status)}>{taskStatusLabels[task.status]}</span></div><p className="text-sm text-blue-600 font-medium">{task.campaigns?.brands?.brand_name ?? 'Brand'} • {task.content_type}</p><p className="text-sm text-slate-600 dark:text-slate-300">{task.content_requirement || 'Không có yêu cầu bổ sung'}</p><div className="flex flex-wrap gap-4 text-xs text-slate-400"><span>Hạn draft: {formatDate(task.draft_deadline)}</span><span>Hạn đăng: {formatDate(task.publish_deadline)}</span><span className="font-semibold text-emerald-600">{formatCurrency(task.payment_amount)}</span></div>{latestDraft?.feedback && <p className="rounded-lg bg-amber-50 dark:bg-amber-900/20 p-3 text-sm text-amber-700 dark:text-amber-300">Phản hồi Brand: {latestDraft.feedback}</p>}</div><div className="shrink-0">{actionFor(task)}</div></div></div>; })}{tasks.length === 0 && <Empty text="Bạn chưa có nhiệm vụ" />}</div><Modal isOpen={action !== null} onClose={() => setAction(null)} title={action?.type === 'draft' ? 'Nộp bản nháp' : action?.type === 'publish' ? 'Gửi bài đã đăng' : 'Báo cáo hiệu suất'}>{action && <ActionForm action={action} close={() => setAction(null)} reload={reload} />}</Modal></div>;
}

function ActionForm({ action, close, reload }: { action: NonNullable<Action>; close: () => void; reload: () => Promise<void> }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [draft, setDraft] = useState({ caption: '', draft_link: '', draft_file_url: '' });
  const [post, setPost] = useState({ post_url: '', publish_time: new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16), screenshot_url: '' });
  const [metric, setMetric] = useState({ report_period: '24H' as ReportPeriod, views: '', likes: '', comments: '', shares: '', saves: '', insight_screenshot_url: '' });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); setError(''); if (action.type === 'draft') await draftService.submitDraft({ task_id: action.task.id, caption: draft.caption || null, draft_link: draft.draft_link || null, draft_file_url: draft.draft_file_url || null }); if (action.type === 'publish') await postService.create({ task_id: action.task.id, post_url: post.post_url, publish_time: new Date(post.publish_time).toISOString(), screenshot_url: post.screenshot_url || null, submitted_at: new Date().toISOString() }); if (action.type === 'metrics') await metricService.submitMetric({ task_id: action.task.id, report_period: metric.report_period, views: Number(metric.views), likes: Number(metric.likes), comments: Number(metric.comments), shares: Number(metric.shares), saves: Number(metric.saves), insight_screenshot_url: metric.insight_screenshot_url || null }); await reload(); close(); } catch (caught) { setError(getErrorMessage(caught)); } finally { setSaving(false); } };
  return <form onSubmit={submit} className="space-y-4">{action.type === 'draft' && <><div><label className="input-label">Caption</label><textarea rows={4} className="input-base" value={draft.caption} onChange={e => setDraft({ ...draft, caption: e.target.value })} /></div><Field label="Link draft" type="url" value={draft.draft_link} set={v => setDraft({ ...draft, draft_link: v })} /><Field label="URL file draft" type="url" value={draft.draft_file_url} set={v => setDraft({ ...draft, draft_file_url: v })} /></>}{action.type === 'publish' && <><Field label="Link bài đăng *" type="url" value={post.post_url} set={v => setPost({ ...post, post_url: v })} /><Field label="Thời gian đăng *" type="datetime-local" value={post.publish_time} set={v => setPost({ ...post, publish_time: v })} /><Field label="URL ảnh chụp màn hình" type="url" value={post.screenshot_url} set={v => setPost({ ...post, screenshot_url: v })} /></>}{action.type === 'metrics' && <><div><label className="input-label">Kỳ báo cáo</label><select className="input-base" value={metric.report_period} onChange={e => setMetric({ ...metric, report_period: e.target.value as ReportPeriod })}>{['24H', '72H', '7DAYS', 'FINAL'].map(p => <option key={p}>{p}</option>)}</select></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{(['views', 'likes', 'comments', 'shares', 'saves'] as const).map(key => <Field key={key} label={key.toUpperCase()} type="number" value={metric[key]} set={v => setMetric({ ...metric, [key]: v })} />)}</div><Field label="URL ảnh insight" type="url" value={metric.insight_screenshot_url} set={v => setMetric({ ...metric, insight_screenshot_url: v })} /></>}{error && <p className="text-sm text-red-500">{error}</p>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={close}>Hủy</Button><button disabled={saving} type="submit" className="btn-primary bg-blue-500 hover:bg-blue-600">{saving ? 'Đang gửi...' : 'Gửi dữ liệu'}</button></div></form>;
}

function Payments({ payments }: { payments: PaymentWithRelations[] }) {
  const total = useMemo(() => payments.reduce((sum, p) => sum + Number(p.paid_amount), 0), [payments]);
  return <div><SectionHeader title="Thanh toán" subtitle={`Tổng đã nhận ${formatCurrency(total)}`} /><div className={`${tableStyles.wrapper} bg-white dark:bg-slate-800`}><table className="w-full"><thead className={tableStyles.thead}><tr>{['Chiến dịch', 'Brand', 'Số tiền', 'Đã nhận', 'Ngày trả', 'Trạng thái'].map(h => <th key={h} className={tableStyles.th}>{h}</th>)}</tr></thead><tbody>{payments.map(payment => <tr key={payment.id} className={tableStyles.tr}><td className={tableStyles.td}>{payment.campaign_tasks?.campaigns?.campaign_name ?? '—'}</td><td className={tableStyles.td}>{payment.brands?.brand_name ?? '—'}</td><td className={tableStyles.td}>{formatCurrency(payment.amount)}</td><td className={tableStyles.td}>{formatCurrency(payment.paid_amount)}</td><td className={tableStyles.td}>{formatDate(payment.paid_date)}</td><td className={tableStyles.td}><span className={statusBadgeClass(payment.status)}>{paymentStatusLabels[payment.status]}</span></td></tr>)}</tbody></table>{payments.length === 0 && <Empty text="Chưa có thông tin thanh toán" />}</div></div>;
}
