import { Award, CheckCircle2, Eye, Heart, Users, ArrowUpRight, ClipboardCheck, Target, BarChart3 } from 'lucide-react';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, ComposedChart, Bar, Area, XAxis, YAxis, CartesianGrid } from 'recharts';
import { Avatar, KPIWidget } from '../../components/SharedUI';
import { campaignStatusLabels, formatCurrency, formatDate, statusBadgeClass } from '../../constants/domain';
import { campaignOutcome, compactNumber, completeStatuses } from '../../utils/analytics';
import type { DataProps } from './BrandDashboard';

const colors = ['#14b8a6', '#4ab1d8', '#f59e0b', '#94a3b8', '#8b5cf6', '#f87171'];
export function BrandOverview({ brand, campaigns, tasks, drafts, metrics, payments, onNavigate }: DataProps & { onNavigate: (view: string) => void }) {
  const outcomes = campaigns.map(c => campaignOutcome(c, tasks));
  const views = outcomes.reduce((s, c) => s + c.views, 0);
  const engagement = outcomes.reduce((s, c) => s + c.engagement, 0);
  const activeTasks = tasks.filter(t => t.status !== 'CANCELLED');
  const creatorRanks = [...new Set(activeTasks.map(t => t.kol_profile_id))].map(id => {
    const rows = outcomes.flatMap(o => o.rows).filter(r => r.task.kol_profile_id === id);
    return { creator: activeTasks.find(t => t.kol_profile_id === id)?.kol_profiles, views: rows.reduce((s, r) => s + r.views, 0) };
  }).sort((a, b) => b.views - a.views);
  const topCampaigns = [...outcomes].sort((a, b) => b.views - a.views).slice(0, 5);
  const distribution = Object.entries(campaignStatusLabels).map(([status, name]) => ({ name, value: campaigns.filter(c => c.status === status).length })).filter(s => s.value > 0);
  const chart = outcomes.map(o => ({ name: o.campaign.campaign_name, views: o.views }));
  const pendingDrafts = drafts.filter(d => d.status === 'SUBMITTED');
  const pendingMetrics = metrics.filter(m => m.status === 'SUBMITTED');
  const pendingPayments = payments.filter(p => p.status !== 'PAID');
  const latestActivities = [
    ...drafts.map(d => ({ key: `draft-${d.id}`, name: d.campaign_tasks?.kol_profiles?.users?.full_name ?? 'Creator', campaign: d.campaign_tasks?.campaigns?.campaign_name, text: d.status === 'SUBMITTED' ? 'Đã nộp bản nháp' : d.status === 'APPROVED' ? 'Draft được duyệt' : 'Cần sửa draft', status: d.status, at: d.reviewed_at ?? d.submitted_at })),
    ...metrics.map(m => ({ key: `metric-${m.id}`, name: m.campaign_tasks?.kol_profiles?.users?.full_name ?? 'Creator', campaign: m.campaign_tasks?.campaigns?.campaign_name, text: m.status === 'APPROVED' ? 'Metrics được duyệt' : m.status === 'REJECTED' ? 'Metrics bị từ chối' : 'Đã gửi metrics', status: m.status, at: m.reviewed_at ?? m.submitted_at })),
    ...tasks.flatMap(t => (t.published_posts ?? []).map(p => ({ key: `post-${p.id}`, name: t.kol_profiles?.users?.full_name ?? 'Creator', campaign: t.campaigns?.campaign_name, text: 'Đã đăng bài', status: 'PUBLISHED', at: p.submitted_at }))),
  ].sort((a, b) => Date.parse(b.at) - Date.parse(a.at)).slice(0, 5);
  const panelTitle = (title: string, view: string) => <div className="flex justify-between items-center gap-2 mb-4"><h3 className="font-semibold text-slate-900 dark:text-white">{title}</h3><button onClick={() => onNavigate(view)} className="text-xs text-teal-600 dark:text-teal-300 flex gap-1 items-center">Xem tất cả <ArrowUpRight className="w-3 h-3" /></button></div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between gap-3 items-end"><div><p className="text-xs uppercase tracking-widest text-teal-600 font-semibold mb-1">Brand workspace</p><h2 className="text-2xl font-display font-bold text-slate-900 dark:text-white">Tổng quan · {brand.brand_name}</h2><p className="text-sm text-slate-500 mt-1">Hiệu suất từ bản báo cáo mới nhất đã được xác minh của mỗi nhiệm vụ.</p></div><button className="btn-primary" onClick={() => onNavigate('campaigns')}>Quản lý chiến dịch <ArrowUpRight className="w-4 h-4" /></button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 2xl:grid-cols-8 gap-3">
      <KPIWidget label="Tổng views" value={compactNumber(views)} icon={<Eye />} />
      <KPIWidget label="Views / bài" value={compactNumber(views / Math.max(1, outcomes.flatMap(o => o.rows).filter(r => r.metric).length))} icon={<BarChart3 />} />
      <KPIWidget label="Tương tác" value={compactNumber(engagement)} icon={<Heart />} />
      <KPIWidget label="Engagement rate" value={views ? `${(engagement / views * 100).toFixed(2)}%` : '—'} icon={<Target />} />
      <KPIWidget label="Chiến dịch" value={String(campaigns.length)} icon={<BarChart3 />} />
      <KPIWidget label="KOL/KOC tham gia" value={String(creatorRanks.length)} icon={<Users />} />
      <KPIWidget label="Task hoàn tất" value={`${activeTasks.filter(t => completeStatuses.has(t.status)).length}/${activeTasks.length}`} icon={<CheckCircle2 />} />
      <KPIWidget label="Creator dẫn đầu" value={creatorRanks[0]?.views ? (creatorRanks[0].creator?.users?.full_name ?? '—').split(' ').slice(0, 2).join(' ') : '—'} icon={<Award />} />
    </div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
      <section className="card-base p-5"><h3 className="font-semibold text-slate-900 dark:text-white">Trạng thái chiến dịch</h3>{distribution.length ? <><div className="h-56"><ResponsiveContainer><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={60} outerRadius={85} paddingAngle={3}>{distribution.map((d, i) => <Cell key={d.name} fill={colors[i % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="space-y-2">{distribution.map((d, i) => <div key={d.name} className="flex items-center gap-2 text-sm"><span className="w-2.5 h-2.5 rounded-full" style={{ background: colors[i % colors.length] }} /><span className="flex-1 text-slate-500">{d.name}</span><b>{d.value}</b></div>)}</div></> : <Empty />}</section>
      <section className="card-base p-5 lg:col-span-2"><div className="flex justify-between gap-2"><h3 className="font-semibold text-slate-900 dark:text-white">Hiệu suất theo chiến dịch</h3><span className="text-xs text-slate-400">Views đã xác minh</span></div>{chart.length ? <div className="h-72 mt-6"><ResponsiveContainer><ComposedChart data={chart} margin={{ top: 5, right: 15, bottom: 10, left: 0 }}><defs><linearGradient id="view-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4ab1d8" stopOpacity={0.25} /><stop offset="100%" stopColor="#4ab1d8" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 10, fill: '#64748b' }} tickFormatter={s => String(s).length > 16 ? `${String(s).slice(0, 16)}…` : String(s)} /><YAxis tick={{ fontSize: 11, fill: '#64748b' }} tickFormatter={compactNumber} width={55} /><Tooltip formatter={(v: number) => [v.toLocaleString('vi-VN'), 'Views']} />{chart.length === 1 ? <Bar dataKey="views" fill="#4ab1d8" barSize={48} radius={[8,8,0,0]} /> : <Area type="monotone" dataKey="views" stroke="#4ab1d8" fill="url(#view-fill)" strokeWidth={2.5} />}</ComposedChart></ResponsiveContainer></div> : <Empty />}</section>
    </div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
      <section className="card-base p-5">{panelTitle('Xếp hạng chiến dịch', 'outcomes')}<p className="text-xs text-slate-400 mb-3">Xếp theo views đã xác minh</p>{topCampaigns.map((o, i) => <div key={o.campaign.id} className="flex gap-3 items-center rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2"><Rank index={i} /><div className="min-w-0 flex-1"><p className="text-sm font-semibold truncate">{o.campaign.campaign_name}</p><p className="text-xs text-slate-400 truncate">{o.campaign.products?.product_name}</p></div><div className="text-right"><b className="text-sm">{compactNumber(o.views)}</b><p className="text-xs text-slate-400">views</p></div></div>)}{!topCampaigns.length && <Empty />}</section>
      <section className="card-base p-5">{panelTitle('Xếp hạng KOL/KOC', 'kol')}<p className="text-xs text-slate-400 mb-3">Creator tham gia các chiến dịch trong bộ lọc</p>{creatorRanks.slice(0, 5).map((r, i) => <div key={r.creator?.id ?? i} className="flex gap-3 items-center rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2"><Rank index={i} /><Avatar size="sm" role="kol" initials={r.creator?.users?.full_name.slice(0, 2) ?? 'KO'} image={r.creator?.users?.avatar_url ?? undefined} /><div className="flex-1 min-w-0"><p className="text-sm font-semibold truncate">{r.creator?.users?.full_name}</p><p className="text-xs text-slate-400">{r.creator?.platform}</p></div><div className="text-right"><b className="text-sm">{compactNumber(r.views)}</b><p className="text-xs text-slate-400">views</p></div></div>)}{!creatorRanks.length && <Empty />}</section>
      <section className="card-base p-5">{panelTitle('Chiến dịch gần đây', 'campaigns')}{campaigns.slice(0, 5).map(c => <div className="flex justify-between items-center gap-3 rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2" key={c.id}><div className="min-w-0"><p className="text-sm font-semibold truncate">{c.campaign_name}</p><p className="text-xs text-slate-400">{c.products?.product_name}</p></div><span className={statusBadgeClass(c.status)}>{campaignStatusLabels[c.status]}</span></div>)}{!campaigns.length && <Empty />}</section>
      <section className="card-base p-5">{panelTitle('Hoạt động gần đây', 'tasks')}{latestActivities.map(a => <div className="flex flex-wrap justify-between items-center gap-2 rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2" key={a.key}><div><p className="text-sm font-semibold">{a.name}</p><p className="text-xs text-slate-400">{a.campaign} · {formatDate(a.at)}</p></div><span className={statusBadgeClass(a.status)}>{a.text}</span></div>)}{!latestActivities.length && <Empty />}</section>
      <section className="card-base p-5">{panelTitle('Nội dung & metrics chờ duyệt', 'content')}<div className="flex gap-2 mb-3"><span className="badge-info">{pendingDrafts.length} draft</span><button onClick={() => onNavigate('performance')} className="badge-warning">{pendingMetrics.length} metrics</button></div>{pendingDrafts.slice(0, 4).map(d => <div className="flex justify-between items-center gap-2 rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2" key={d.id}><div><p className="text-sm font-semibold">{d.campaign_tasks?.kol_profiles?.users?.full_name}</p><p className="text-xs text-slate-400">{d.campaign_tasks?.campaigns?.campaign_name}</p></div><ClipboardCheck className="w-4 h-4 text-teal-600" /></div>)}{!pendingDrafts.length && <p className="text-sm text-slate-400 py-4">Không có draft đang chờ duyệt.</p>}</section>
      <section className="card-base p-5">{panelTitle('Thanh toán chưa hoàn tất', 'payment')}<p className="text-lg font-bold text-teal-600 mb-3">{formatCurrency(pendingPayments.reduce((s, p) => s + Math.max(0, Number(p.amount) - Number(p.paid_amount)), 0))}</p>{pendingPayments.slice(0, 4).map(p => <div className="flex justify-between gap-2 rounded-xl bg-slate-50 dark:bg-slate-900/40 p-3 mb-2" key={p.id}><div><p className="text-sm font-semibold">{p.kol_profiles?.users?.full_name}</p><p className="text-xs text-slate-400">{p.campaign_tasks?.campaigns?.campaign_name}</p></div><span className="text-sm font-medium">{formatCurrency(Number(p.amount) - Number(p.paid_amount))}</span></div>)}{!pendingPayments.length && <Empty />}</section>
    </div>
    <p className="text-xs text-slate-400">Conversion chưa được ghi nhận trong schema hiện tại. Không cộng các báo cáo tích lũy của cùng một task.</p>
  </div>;
}
function Empty() { return <p className="text-sm text-slate-400 py-12 text-center">Chưa có dữ liệu trong bộ lọc này.</p>; }
function Rank({ index }: { index: number }) { return <span className={`w-8 h-8 rounded-full shrink-0 flex items-center justify-center text-sm font-bold ${index === 0 ? 'bg-amber-500 text-white' : index === 1 ? 'bg-slate-400 text-white' : index === 2 ? 'bg-amber-700 text-white' : 'bg-slate-200 text-slate-600 dark:bg-slate-700 dark:text-slate-200'}`}>{index + 1}</span>; }
