import { useState } from 'react';
import { Download, ExternalLink, Eye, Heart, Users, Wallet } from 'lucide-react';
import { KPIWidget, tableStyles } from '../../components/SharedUI';
import { campaignStatusLabels, formatCurrency, formatDate, metricStatusLabels, statusBadgeClass, taskStatusLabels } from '../../constants/domain';
import type { CampaignWithRelations, TaskWithRelations } from '../../types/database';
import { campaignOutcome, compactNumber, downloadCsv, taskOutcome } from '../../utils/analytics';

export function CampaignOutcome({ campaign, tasks }: { campaign: CampaignWithRelations; tasks: TaskWithRelations[] }) {
  const [verifiedOnly, setVerifiedOnly] = useState(true);
  const o = campaignOutcome(campaign, tasks, verifiedOnly);
  const exportReport = () => downloadCsv(`campaign-${campaign.id}-outcome.csv`, [
    ['Chiến dịch', campaign.campaign_name], ['Cơ sở số liệu', verifiedOnly ? 'Đã xác minh' : 'Bao gồm báo cáo chờ duyệt'],
    ['Views', o.views], ['Tương tác', o.engagement], ['ER (%)', o.er.toFixed(2)], ['Ngân sách', campaign.budget], ['Đã trả', o.paid],
    ['Creator', 'Task', 'Trạng thái', 'Kỳ báo cáo', 'Views', 'Likes', 'Comments', 'Shares', 'Saves', 'Trạng thái metrics', 'Thù lao', 'Đã trả', 'Link bài đăng'],
    ...o.tasks.map(task => { const r = o.rows.find(row => row.task.id === task.id); const m = r?.metric; return [task.kol_profiles?.users?.full_name ?? '', task.id, task.status, m?.report_period ?? '', m?.views ?? '', m?.likes ?? '', m?.comments ?? '', m?.shares ?? '', m?.saves ?? '', m?.status ?? '', task.payment_amount, taskOutcome(task).paid, task.published_posts?.[0]?.post_url ?? '']; }),
  ]);
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-bold text-slate-900 dark:text-white">{campaign.campaign_name}</h3><p className="text-sm text-slate-500 mt-1">{campaign.products?.product_name} · {formatDate(campaign.start_date)} – {formatDate(campaign.end_date)}</p></div><span className={statusBadgeClass(campaign.status)}>{campaignStatusLabels[campaign.status]}</span></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={verifiedOnly} onChange={e => setVerifiedOnly(e.target.checked)} className="accent-teal-600" />Chỉ tính metrics đã được Brand duyệt</label><button className="btn-secondary" onClick={exportReport}><Download className="w-4 h-4" />Xuất CSV</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><KPIWidget label="Views" value={compactNumber(o.views)} icon={<Eye />} /><KPIWidget label="Tương tác" value={compactNumber(o.engagement)} icon={<Heart />} /><KPIWidget label="ER" value={o.hasMetrics ? `${o.er.toFixed(2)}%` : '—'} icon={<Users />} /><KPIWidget label="Đã thanh toán" value={formatCurrency(o.paid)} icon={<Wallet />} /></div>
    <div className="grid sm:grid-cols-2 gap-4">
      <section className="surface-subtle p-4 space-y-3"><h4 className="font-semibold">Mục tiêu & kết quả</h4><p className="text-sm">{campaign.objective || 'Chưa có mục tiêu mô tả.'}</p><div className="flex justify-between text-sm"><span>Views thực tế / mục tiêu</span><b>{o.views.toLocaleString('vi-VN')} / {campaign.target_views.toLocaleString('vi-VN')}</b></div><div className="h-2 rounded-full bg-slate-200 dark:bg-slate-700"><div className="h-2 rounded-full bg-teal-500" style={{ width: `${Math.min(100, o.targetProgress ?? 0)}%` }} /></div><p className="text-xs text-slate-500">{o.targetProgress === null ? 'Chưa đặt target views' : `${o.targetProgress.toFixed(1)}% mục tiêu views`}</p><p className="text-sm">Target ER: <b>{campaign.target_engagement_rate}%</b> · Thực tế: <b>{o.hasMetrics ? `${o.er.toFixed(2)}%` : 'Chưa có metrics'}</b></p><p className="text-sm">Target conversion: <b>{campaign.target_conversion}</b> · Thực tế: <span className="text-slate-500">Chưa thu thập conversion</span></p></section>
      <section className="surface-subtle p-4 space-y-3"><h4 className="font-semibold">Ngân sách & tiến độ</h4><p className="text-sm flex justify-between">Ngân sách <b>{formatCurrency(campaign.budget)}</b></p><p className="text-sm flex justify-between">Thù lao đã giao <b>{formatCurrency(o.committed)}</b></p><p className="text-sm flex justify-between">Còn phải trả theo task <b>{formatCurrency(o.outstanding)}</b></p><p className="text-sm">{o.published} bài đã đăng · {o.completed}/{o.rows.length} task hoàn tất</p><p className="text-xs text-slate-500">CPV theo tiền đã trả: {o.cpv === null ? 'Chưa đủ dữ liệu' : formatCurrency(o.cpv)} · CPE: {o.cpe === null ? 'Chưa đủ dữ liệu' : formatCurrency(o.cpe)}</p>{o.committed > campaign.budget && <p className="text-sm text-amber-600">Thù lao được giao đang vượt ngân sách chiến dịch.</p>}</section>
    </div>
    <p className="text-xs text-slate-500">Lấy một báo cáo mới nhất theo thời gian gửi cho mỗi task; loại báo cáo bị từ chối và task đã hủy khỏi tổng hiệu suất. {verifiedOnly ? 'Báo cáo chờ duyệt chưa được tính.' : 'Số liệu bao gồm báo cáo chưa được xác minh.'}</p>
    <div className={tableStyles.wrapper}><table className="w-full"><thead className={tableStyles.thead}><tr>{['Creator / Task', 'Trạng thái', 'Bài đăng', 'Metrics mới nhất', 'Views', 'Likes / Comments', 'Shares / Saves', 'Thù lao / Đã trả'].map(h => <th key={h} className={tableStyles.th}>{h}</th>)}</tr></thead><tbody>{o.tasks.map(t => { const row = o.rows.find(r => r.task.id === t.id); const m = row?.metric; return <tr key={t.id} className={tableStyles.tr}><td className={tableStyles.td}><p className="font-semibold">{t.kol_profiles?.users?.full_name}</p><p className="text-xs text-slate-400">#{t.id} · {t.content_type}</p><p className="text-xs text-slate-400">Hạn đăng {formatDate(t.publish_deadline)}</p></td><td className={tableStyles.td}><span className={statusBadgeClass(t.status)}>{taskStatusLabels[t.status]}</span></td><td className={tableStyles.td}>{t.published_posts?.length ? t.published_posts.map(p => <a key={p.id} href={p.post_url} target="_blank" rel="noreferrer" className="text-teal-600 flex items-center gap-1 mb-1">Mở bài <ExternalLink className="w-3 h-3" /></a>) : 'Chưa đăng'}</td><td className={tableStyles.td}>{m ? <><p>{m.report_period} · {formatDate(m.submitted_at)}</p><span className={statusBadgeClass(m.status)}>{metricStatusLabels[m.status]}</span></> : 'Chưa có'}</td><td className={tableStyles.td}>{m ? m.views.toLocaleString('vi-VN') : '—'}</td><td className={tableStyles.td}>{m ? `${m.likes.toLocaleString('vi-VN')} / ${m.comments.toLocaleString('vi-VN')}` : '—'}</td><td className={tableStyles.td}>{m ? `${m.shares.toLocaleString('vi-VN')} / ${m.saves.toLocaleString('vi-VN')}` : '—'}</td><td className={tableStyles.td}>{formatCurrency(t.payment_amount)}<p className="text-xs text-teal-600">Đã trả {formatCurrency(taskOutcome(t).paid)}</p></td></tr>; })}</tbody></table>{!o.tasks.length && <p className="p-8 text-center text-sm text-slate-400">Chưa phân công nhiệm vụ.</p>}</div>
    <details className="card-base p-4"><summary className="cursor-pointer font-semibold text-sm">Brief & lịch sử review</summary><p className="text-sm mt-3 whitespace-pre-wrap">{campaign.campaign_brief || 'Chưa có brief.'}</p>{o.tasks.map(t => <div key={t.id} className="mt-4 text-sm"><p className="font-semibold">{t.kol_profiles?.users?.full_name}</p>{[...(t.draft_submissions ?? [])].sort((a, b) => Date.parse(b.submitted_at) - Date.parse(a.submitted_at)).map(d => <p key={d.id} className="text-slate-500 mt-1">{formatDate(d.submitted_at)} · Draft {d.status} · {d.feedback || 'Chưa có feedback'}</p>)}{[...(t.performance_metrics ?? [])].sort((a, b) => Date.parse(b.submitted_at) - Date.parse(a.submitted_at)).map(m => <p key={m.id} className="text-slate-500 mt-1">{formatDate(m.submitted_at)} · Metrics {m.report_period} · {metricStatusLabels[m.status]} · {m.feedback || ''}</p>)}</div>)}</details>
  </div>;
}
